on: [push]
name: AzureARMSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.anilsc }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: anil3333
        template: ./template.json
       
