on: [push]

name: AzureARMDeploy

jobs:
  
 deploy:
   runs-on: ubuntu-latest
   steps:

   - name: Login to Azure           
     uses: azure/login@v1
     with:
        creds: ${{ secrets.anilsc }}
    
   
      
   - name: ARM deployement
     uses: azure/arm-deploy@v1
     with:
            resourceGroupName: anil3333
            template: . /template.json
            
